# Generated by Django 4.1.7 on 2023-02-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_shifts_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifts",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="core.employees",
            ),
        ),
    ]
